Altinn/altinn-components

- .github/workflows/ci-cd-main.yml
> ci: setup pnpm

- .github/workflows/ci-cd-main.yml
> ci: setup pnpm if condition

- package.json
> chore: fix npm publishing

- .gitignore
- CONTRIBUTING.MD
- README.md
- package.json
> doc: add documentation for project + contributing

- lib/components/Dialog/DialogListItem.stories.tsx
- lib/components/Dialog/DialogSelect.tsx
- lib/components/Dialog/dialogHeadings.module.css
- lib/components/Dialog/dialogListItemBase.module.css
- lib/components/Dialog/dialogSelect.module.css
- lib/components/Icon/CheckboxCheckedIcon.tsx
- lib/components/Icon/CheckboxIcon.stories.ts
- lib/components/Icon/CheckboxIcon.tsx
- lib/components/Icon/CheckboxUncheckedIcon.tsx
- lib/components/Icon/RadioCheckedIcon.tsx
- lib/components/Icon/RadioIcon.stories.ts
- lib/components/Icon/RadioIcon.tsx
- lib/components/Icon/RadioUncheckedIcon.tsx
- lib/components/Icon/checkboxIcon.module.css
- lib/components/Menu/MenuOption.tsx
- lib/components/Menu/menuOption.module.css
> fix:checkboxes+radio icons

- lib/components/ContextMenu/ContextMenu.tsx
- lib/components/Dialog/Dialog.stories.ts
- lib/components/Dialog/Dialog.tsx
- lib/components/Dialog/DialogContent.tsx
- lib/components/Dialog/DialogNav.tsx
> fix:dialog-props

- .github/workflows/ci-cd-deploy-storybook.yml
> Chore: fix deploy storybook gp

- .github/workflows/ci-cd-deploy-storybook.yml
> chore(ci): change step for preparing folder for gh pages upload

- .github/workflows/ci-cd-deploy-storybook.yml
> chore(ci): simplify step for uploading storybook artifact

- .github/workflows/ci-cd-deploy-storybook.yml
- README.md
> chore: fix artifact unable to upload storybook to gh pages

- .github/workflows/ci-cd-main.yml
- .github/workflows/workflow-deploy-storybook.yml
- Refactor publish to gh-pages to a reusable workflows and fix trigger from the CI/CD main workflow
- Rename main workflow to CI/CD Main
> ci: cleanup workflows

- lib/components/Footer/Footer.stories.ts
- lib/components/Footer/Footer.tsx
- lib/components/Footer/FooterAddress.tsx
- lib/components/Footer/FooterBase.tsx
- lib/components/Footer/FooterLogo.tsx
- lib/components/Footer/FooterMenu.tsx
- lib/components/Footer/footerAddress.module.css
- lib/components/Footer/footerBase.module.css
- lib/components/Footer/footerLogo.module.css
- lib/components/Footer/footerMenu.module.css
- lib/components/Footer/index.ts
- lib/components/Layout/Layout.stories.tsx
- lib/components/Layout/Layout.tsx
- lib/components/index.ts
> feat: add footer

- .storybook/main.ts
- lib/components/Dialog/DialogListItem.tsx
- lib/components/Dialog/DialogNav.tsx
- lib/components/Dialog/dialogNav.module.css
- lib/components/Header/Header.tsx
- lib/components/History/HistoryAttachments.tsx
- lib/components/History/HistoryItem.stories.ts
- lib/components/History/HistoryItem.tsx
- lib/components/History/HistoryList.stories.ts
- lib/components/Layout/LayoutBase.tsx
- lib/components/Layout/index.tsx
- lib/components/Layout/layoutBase.module.css
- lib/components/Layout/layoutContent.module.css
- lib/components/Layout/layoutSidebar.module.css
- lib/components/LayoutAction/ActionFooter.stories.tsx
- lib/components/LayoutAction/ActionHeader.tsx
- lib/components/LayoutAction/ActionMenu.stories.tsx
- lib/components/LayoutAction/ActionMenu.tsx
- lib/components/LayoutAction/actionMenu.module.css
- lib/components/Menu/MenuItem.stories.tsx
- lib/components/Menu/MenuItemBase.tsx
- lib/components/Menu/__menuItem.module.css
- lib/components/Menu/menuItemBase.module.css
- lib/components/Menu/menuItemMedia.module.css
- lib/css/global.css
- lib/css/theme-global-dark.css
> fix: changes to css for dialogs 

- lib/components/GlobalMenu/AccountButton.tsx
- lib/components/GlobalMenu/AccountMenu.tsx
- lib/components/GlobalMenu/GlobalMenu.stories.tsx
- lib/components/GlobalMenu/GlobalMenu.tsx
- lib/components/Header/Header.stories.tsx
- lib/components/Header/Header.tsx
- lib/components/Layout/Layout.stories.tsx
- lib/stories/Inbox/InboxLayout.tsx
- lib/stories/Inbox/InboxProvider.tsx
> fix: suggestion of fixing selecting current account

- package.json
> fix: publish npm: revert to old working export

- package.json
- pnpm-lock.yaml
- vite.config.ts
> chore: keep use strict for files

- lib/components/List/ListItem.stories.tsx
- lib/components/List/listItemBase.module.css
> fix: list item base reset

- lib/components/ContextMenu/ContextMenu.tsx
- lib/components/Layout/Layout.tsx
> fix: add use client directives on the last files using useContext

- lib/components/GlobalMenu/AccountMenu.stories.tsx
- lib/components/GlobalMenu/GlobalMenu.tsx
- lib/components/GlobalMenu/index.tsx
- lib/components/Header/Header.stories.tsx
- lib/components/List/listItemBase.module.css
- lib/components/Menu/menuItemBase.module.css
> fix: menuitem base + onSelectAccount

- lib/components/List/listItemBase.module.css
- lib/components/Menu/menuItemBase.module.css
> fix: reset menu + list item

- lib/components/Menu/MenuItemMedia.tsx
- lib/components/Menu/menuItemBase.module.css
> fix: menu item padding

- lib/components/Menu/menuOption.module.css
- lib/components/Toolbar/Toolbar.stories.tsx
> fix: menu-options flex

- lib/components/Footer/FooterMenu.tsx
- lib/components/Footer/footerBase.module.css
> fix: footer widths

- lib/components/Header/Header.tsx
Needed in order to render link in logo as Link.
> fix: allow customization of logo props from HeaderProps

- README.md
Update doc in addition. Make fix to trigger ned release.
> fix: header logo is used from header props

- lib/components/GlobalMenu/AccountMenu.tsx
- lib/components/GlobalMenu/GlobalMenu.stories.tsx
- lib/components/Menu/MenuItems.tsx
https://github.com/Altinn/altinn-components/issues/110
> fix: remove unwanted list item when account search returns no hits

- lib/components/GlobalMenu/AccountMenu.stories.tsx
- lib/components/GlobalMenu/AccountMenu.tsx
- package.json
> fix: add badge and avatar groups for account menu item

- lib/components/GlobalMenu/globalMenuBase.module.css
- lib/components/Header/Header.tsx
- lib/components/Header/header.module.css
- lib/components/Layout/Layout.stories.tsx
- lib/components/Layout/layoutBase.module.css
- lib/components/Menu/MenuItems.tsx
> fix: drawer menu not showing

- lib/components/List/ListItem.tsx
> fix: list item “as” prop was not sent to ListItemHeader

- lib/components/AccessAreaList/AccessAreaList.tsx
- lib/components/AccessAreaList/AccessAreaListItem.stories.tsx
- lib/components/AccessPackageList/AccessPackageList.stories.tsx
- lib/components/Autocomplete/Autocomplete.stories.tsx
- lib/components/Autocomplete/AutocompleteItem.tsx
- lib/components/Bookmarks/BookmarksList.stories.tsx
- lib/components/Bookmarks/BookmarksList.tsx
- lib/components/Bookmarks/BookmarksListItem.stories.tsx
- lib/components/Bookmarks/BookmarksSection.stories.tsx
- lib/components/Button/Buttons.stories.tsx
- lib/components/Button/IconButton.stories.tsx
- lib/components/Button/IconButton.tsx
- lib/components/Byline/Byline.tsx
- lib/components/Dialog/DialogListItem.stories.tsx
- lib/components/Dialog/DraftDialog.stories.tsx
- lib/components/Dialog/DraftDialog.tsx
- lib/components/GlobalMenu/GlobalMenu.stories.tsx
- lib/components/Header/Header.stories.tsx
- lib/components/Layout/Layout.stories.tsx
- lib/components/LayoutAction/ActionFooter.stories.tsx
- lib/components/Page/PageBase.stories.tsx
- lib/components/Searchbar/Searchbar.stories.tsx
- lib/components/Snackbar/Snackbar.stories.tsx
- lib/components/Snackbar/Snackbar.tsx
- lib/examples/useInboxSearch.tsx
- lib/stories/Inbox/BookmarksPage.tsx
- lib/stories/Inbox/InboxToolbar.tsx
- tsconfig.json
> chore: Include ./lib/**/*.tsx to tsconfig and fix all ts errors

- .storybook/main.ts
- lib/components/ContextMenu/ContextMenu.tsx
- lib/components/GlobalMenu/GlobalMenu.tsx
- lib/components/Header/Header.tsx
- package.json
- pnpm-lock.yaml
> fix: make context menu and global menu (top level) dismiss on menu item click

- lib/components/Autocomplete/index.ts
- package.json
- vite.config.ts
> fix: types were not properly exported

- README.md
> chore(doc): fix typo in doc

- .github/workflows/storybook-tests.yml
- CONTRIBUTING.MD
- lib/components/Button/IconButton.tsx
- lib/components/ContextMenu/ContextMenu.stories.ts
- lib/components/Dropdown/DropdownBase.tsx
- lib/components/Searchbar/SearchField.tsx
- lib/components/Searchbar/Searchbar.stories.tsx
- package.json
- pnpm-lock.yaml
> chore: add Storybook Test Runner for Component Library

- lib/components/Bookmarks/BookmarksListItem.stories.tsx
- lib/components/Bookmarks/BookmarksListItem.tsx
- lib/components/Bookmarks/BookmarksSection.stories.tsx
- lib/components/Bookmarks/BookmarksSection.tsx
- package.json
> fix: move remove and save button to items for bookmark + add as

- lib/components/Autocomplete/Autocomplete.stories.tsx
- lib/components/Bookmarks/BookmarksListItem.tsx
- lib/components/Bookmarks/BookmarksSection.stories.tsx
- package.json
> fix: add onChange and inputValue for bookmarksection textfield

- lib/components/GlobalMenu/GlobalMenu.tsx
> fix: close menu on desktop when account is selected from global menu

- lib/components/Snackbar/index.ts
> fix: Add useSnackbar export

- lib/components/Snackbar/index.ts
> fix: remove uncommented exports for snackbar

- lib/components/AccessAreaList/index.ts
- lib/components/Attachment/AttachmentLink.tsx
- lib/components/Autocomplete/AutocompleteBase.tsx
- lib/components/Avatar/AvatarGroup.tsx
> fix: missing exports for some components

- vite.config.ts
> fix: remove react and react-dom as dependencies

- lib/components/Layout/layoutBody.module.css
- lib/components/Page/flex.module.css
- lib/components/Page/grid.module.css
> fix: adjust max-height for desktop media query on layout properties

- README.md
First attempt to clarify the purpose of the library. 
- #184
> chore(doc): clarify vision / goal in README

- .storybook/StoryDecorator.tsx
- .storybook/preview.tsx
- lib/components/Header/Header.stories.tsx
- lib/components/Layout/Layout.mdx
- lib/components/Layout/Layout.stories.tsx
- lib/components/Layout/Layout.tsx
- lib/components/LayoutAction/LayoutAction.stories.tsx
- lib/components/List/List.mdx
- lib/components/Menu/Menu.mdx
- lib/components/Snackbar/SnackbarItem.stories.tsx
- package.json
> doc: layout stories

- release-please-config.json
> chore: ensure correct release strategy

- lib/components/Menu/MenuOption.tsx
- lib/components/Toolbar/Toolbar.mdx
- lib/components/Toolbar/Toolbar.stories.tsx
- lib/components/Toolbar/ToolbarOptions.stories.ts
- lib/components/Toolbar/ToolbarOptions.tsx
> doc: Toolbar story

- lib/components/Bookmarks/EditableBookmark.tsx
> fix: should show chevron-up if expanded in BookmarksListItem

- lib/components/Search/Autocomplete.tsx
- package.json
> fix: on enter not working in auto complete

- lib/components/Dropdown/DrawerBase.tsx
- lib/components/Dropdown/DropdownBase.tsx
- lib/components/Dropdown/drawerBase.module.css
- lib/components/Dropdown/drawerOrDropdown.module.css
- lib/components/Dropdown/dropdownBase.module.css
- lib/components/GlobalMenu/globalMenuBase.module.css
- lib/components/Header/header.module.css
- package.json
> fix: drawer layout issues after aria-expanded was removed

- .storybook/test-runner.ts
- package.json
- pnpm-lock.yaml
> chore: fix error running axe-playwright by forcing max-workers to 1 for now

- README.md
Noticed that the README has the wrong repo name in the installation guide.
This is now corrected
> fix: Fix instructions in readme

- lib/components/List/ListBase.stories.tsx
- lib/components/List/ListItem.mdx
- package.json
> fix: list story

- lib/components/Toolbar/Toolbar.stories.tsx
- lib/components/Toolbar/ToolbarAccountMenu.tsx
- package.json
Close account menu when selecting an account in Toolbar
> fix: close account menu in toolbar when selected

- lib/components/Search/Autocomplete.tsx
- package.json
> fix: Keyboard onEnter unintentionally opens search bar

- lib/components/Toolbar/Toolbar.tsx
> fix: add addFilterButtonLabel prop to Toolbar in order to override add filter label

- lib/components/Dialog/DialogListGroup.tsx
- lib/components/Search/SearchField.tsx
- lib/stories/Demo/inbox/InboxSection.tsx
> fix: make checkbox and its label in DialogListGroup optional

- lib/components/Attachment/AttachmentLink.tsx
> fix: Open dialog attachments in new tab

- lib/components/Dialog/DialogContent.tsx
- lib/components/Timeline/TimelineSection.tsx
- lib/components/Timeline/timelineSection.module.css
- package.json
> fix: add isSeenByEndUser for TimelineSection

- lib/components/Dialog/DialogBody.tsx
> fix: add isSeenByDialog on DialogBody

- lib/components/Header/Header.tsx
> fix: Close menu when selecting an item from global menu on mobile

- lib/components/List/ListItem.stories.tsx
- lib/components/List/ListItem.tsx
- lib/components/List/listItemBase.module.css
- lib/components/Menu/MenuItemBase.tsx
- lib/components/Menu/menuItemBase.module.css
add [aria-selected] to selected menu item
> fix: menu item selected

- lib/components/Dialog/DialogActions.tsx
> fix: add missing button props to gui action buttons

- lib/components/Page/PageTabs.stories.tsx
- lib/components/Page/PageTabs.tsx
- lib/components/Page/pageTabs.module.css
- package.json
> fix: Page tabs selected

- examples/dialog/dialogListItems.ts
- lib/components/Dialog/DialogList.stories.tsx
- lib/components/Dialog/DialogList.tsx
- lib/hooks/useMenu.tsx
https://github.com/Altinn/dialogporten-frontend/issues/1848
> fix: Sort dialog list by date desc

- lib/components/Page/Flex.tsx
- lib/components/Page/flex.module.css
- lib/components/Timeline/Timeline.stories.tsx
- lib/components/Timeline/Timeline.tsx
- lib/components/Timeline/TimelineActivity.tsx
- lib/components/Timeline/TimelineSegment.tsx
- lib/components/Timeline/index.ts
- lib/components/Typography/typography.module.css
- lib/hooks/useMenu.tsx
> Timeline segments

- lib/components/Page/BreadcrumbsLink.tsx
> fix: breacrumbs href/rest

- lib/components/ContextMenu/ContextMenu.stories.tsx
- lib/components/Dialog/DialogActions.tsx
- lib/components/Search/Searchbar.stories.tsx
> fix(DialogActions): make dismissable with escape or click-away

- lib/components/Avatar/Avatar.tsx
- lib/hooks/useClickOutside.ts
- package.json
- pnpm-lock.yaml
> feat: update to React 19

- lib/components/Dialog/DialogBody.mdx
- lib/components/Dialog/DialogBody.stories.tsx
- lib/components/Dialog/DialogList.mdx
- lib/components/Dialog/DialogList.stories.tsx
- lib/components/Dialog/DialogListItem.mdx
- lib/components/Dialog/DialogListItem.stories.tsx
- lib/components/Dialog/DialogListItem.tsx
- lib/components/Dialog/DialogMetadata.mdx
- lib/components/Dialog/dialogListItem.module.css
> doc: dialog stories + dashed draft border

- lib/components/Button/ButtonBase.tsx
- lib/components/Button/ButtonIcon.tsx
- lib/components/Button/buttonBase.module.css
- lib/components/Byline/Byline.tsx
- lib/components/List/ListItemLabel.tsx
- lib/components/List/listItemLabel.module.css
- lib/components/Page/Flex.tsx
- lib/components/Timeline/Timeline.stories.tsx
- lib/components/Timeline/Timeline.tsx
- lib/components/Timeline/TimelineBase.tsx
- lib/components/Timeline/TimelineFooter.tsx
- lib/components/Timeline/TimelineHeader.tsx
- lib/components/Timeline/TimelineLink.tsx
- lib/components/Timeline/TimelineSection.tsx
- lib/components/Timeline/TimelineSegment.tsx
- lib/components/Timeline/index.ts
- lib/components/Timeline/timelineBase.module.css
- lib/components/Timeline/timelineLink.module.css
- lib/components/Transmission/Transmission.tsx
- lib/components/Transmission/TransmissionTimeline.stories.tsx
- lib/components/Transmission/TransmissionTimeline.tsx
- lib/components/Transmission/TransmissionTimelineSegment.tsx
- lib/components/Transmission/index.ts
- lib/stories/Demo/data/dialog/transmissionList.ts
- package.json
> feat: Transmission timeline

- .storybook/preview-head.html
- README.md
- lib/css/global.css
> fix: drop import of fonts

- lib/components/Menu/menuItemBase.module.css
> fix: menu item color + font

- lib/components/Dialog/DialogActions.stories.ts
- lib/components/Dialog/DialogActions.tsx
https://github.com/Altinn/dialogporten-frontend/issues/1812
> fix: Add hiden support for dialog actions

- lib/components/Dialog/DialogActions.tsx
https://github.com/Altinn/dialogporten-frontend/issues/1812
> fix: filter out hidden dialog actions

- lib/components/Dialog/DialogHistory.mdx
> doc: the anatomy of dialog history

- .storybook/main.ts
- lib/css/padding.css
- lib/css/shadow.css
- lib/css/spacing.css
Solves issue with unwanted cascading where padding, margins and shadows are being overridden. 
> fix: general-purpose global selectors should be more precise and part of the root

- lib/components/Dialog/DialogLayout.tsx
- package.json
move theme from pagemenu to pagebase
> fix: dialog shadow

- examples/dialog/inboxSection.tsx
- lib/components/Bookmarks/BookmarksListItem.tsx
- lib/components/Bookmarks/EditableBookmark.tsx
- lib/components/Dialog/DialogListItem.stories.tsx
- lib/components/Dialog/DialogListItem.tsx
- lib/components/Dialog/dialogListItem.module.css
- lib/components/Dropdown/dropdownBase.module.css
- lib/components/List/ListItem.stories.tsx
- lib/components/List/ListItem.tsx
- lib/components/List/ListItemBase.tsx
- lib/components/List/ListItemHeader.tsx
- lib/components/List/ListItemLabel.tsx
- lib/components/List/ListItemLink.tsx
- lib/components/List/Patterns.mdx
- lib/components/List/Patterns.stories.tsx
- lib/components/List/listItemBase.module.css
- lib/components/List/listItemHeader.module.css
- lib/components/List/listItemLink.module.css
- lib/components/ResourceList/ResourceListItem.stories.tsx
- lib/components/Search/Autocomplete.tsx
- lib/components/Search/AutocompleteItem.tsx
- lib/components/Search/Searchbar.stories.tsx
Expand clickable area for ListItem with a simplified structure - making entire header clickable without interference with controls.
- #305
> fix: expand clickable area for ListItem

- examples/dialog/transmissions.tsx
- lib/components/Bookmarks/BookmarksSection.stories.tsx
- lib/components/Dialog/DialogHistoryItem.tsx
- lib/components/List/ListItem.tsx
- lib/components/List/ListItemHeader.tsx
- lib/components/List/listItemHeader.module.css
- lib/components/Transmission/Transmission.tsx
> fix: add children to transmission

- lib/components/Transmission/Transmission.tsx
> fix: transmission should be button for interactive

- lib/components/Dialog/DialogBody.tsx
- lib/components/Page/ContactSection.tsx
- lib/components/Typography/Typography.tsx
- lib/components/Typography/typography.module.css
- package.json
> fix: typography max width

- lib/components/Search/Autocomplete.stories.tsx
- lib/components/Search/AutocompleteItem.tsx
- lib/components/Search/SuggestListItem.tsx
> fix: autocomplete suggest tyoe did not respect as prop

- lib/components/Search/Autocomplete.stories.tsx
- lib/components/Search/ScopeListItem.tsx
- lib/components/Search/Searchbar.stories.tsx
> fix: autocomplete of type scope lost its as-prop on the way

- lib/components/List/ListItem.stories.tsx
Add OverideTitleAs story to demonstrate titleAs prop variations in ListItem
> fix : add OverideTitleAs story to demonstrate titleAs prop variations in ListItem

- lib/components/List/ListItem.stories.tsx
> fix: trigger release

- examples/accountMenu.tsx
- lib/components/GlobalMenu/AccountMenu.tsx
- lib/components/Menu/Menu.tsx
- lib/components/Menu/MenuBase.tsx
- lib/components/Menu/MenuItemsVirtual.tsx
- lib/components/Menu/menuItemsVirtual.module.css
- lib/components/Toolbar/Toolbar.stories.tsx
- lib/components/Toolbar/ToolbarAccountMenu.tsx
- package.json
- pnpm-lock.yaml
Research for virtualising long lists with react-window/react-virtualized/tanstack-virtual and implementation. 
https://github.com/Altinn/dialogporten-frontend/issues/1617
> feat: Implement virtualiser for long lists

- lib/components/Menu/MenuItemBase.tsx
- lib/components/Menu/menuItemBase.module.css
- package.json
> fix: account button padding

- examples/globalMenu.ts
- lib/components/GlobalMenu/GlobalMenu.tsx
https://github.com/Altinn/dialogporten-frontend/issues/1617
> fix: Include list virtualization in accounts in header menu

- lib/components/List/ListItem.stories.tsx
- lib/components/List/ListItem.tsx
- lib/components/List/listItemLink.module.css
- lib/components/Search/Autocomplete.stories.tsx
- lib/components/Search/AutocompleteItem.tsx
- package.json
It also adds pointer to interactive items.
- #354 
- #353
> fix: ListItemBase was not passed interactive from parent, resulting in interactive always true

- lib/components/Snackbar/snackbarBase.module.css
> fix: snackbar z-index

- lib/components/Header/Header.stories.tsx
- lib/components/Header/Header.tsx
- lib/components/Header/LocaleSwitcher.tsx
- lib/components/Header/header.module.css
Locale swticher button was rendered always
> fix: small fixes to locale switcher

- examples/accountMenu.tsx
- lib/components/GlobalMenu/AccountMenu.tsx
- package.json
> fix: add support for account groups of companies and people

- examples/globalMenu.ts
- lib/components/GlobalMenu/AccountButton.tsx
- lib/components/GlobalMenu/EndUserLabel.tsx
- lib/components/GlobalMenu/GlobalMenu.stories.tsx
- lib/components/GlobalMenu/GlobalMenu.tsx
- lib/components/GlobalMenu/GlobalMenuBase.tsx
- lib/components/GlobalMenu/accountButton.module.css
- lib/components/GlobalMenu/endUserLabel.module.css
- lib/components/GlobalMenu/globalMenuBase.module.css
- lib/components/GlobalMenu/index.tsx
- lib/components/Menu/MenuItemLabel.tsx
- lib/components/Menu/menuItemBase.module.css
- lib/components/Menu/menuItemLabel.module.css
- package.json
> fix: global menu details

- README.md
> doc: clarify strategy on how we are adopting Designsystemet

- lib/components/Header/LocaleSwitcher.tsx
https://github.com/Altinn/altinn-components/issues/394
> fix: Close localeSwitcher after choosing language

- lib/components/Toolbar/Toolbar.stories.tsx
- lib/components/Toolbar/Toolbar.tsx
- lib/components/Toolbar/ToolbarDate.stories.ts
- lib/components/Toolbar/ToolbarFilter.tsx
- lib/components/Toolbar/ToolbarOptions.stories.ts
- lib/components/Toolbar/ToolbarOptions.tsx
> fix: updated filters does not update toolbar

- examples/adminMenu.tsx
- examples/index.ts
- examples/profileMenu.tsx
- examples/useAdminLayout.tsx
- examples/useCategoryLayout.tsx
- examples/useProfileLayout.tsx
- lib/components/Page/Patterns.stories.tsx
> doc: add layout to page examples

- lib/components/Profile/AccountList.tsx
> Fix: children for account list

- lib/components/DsComponents/index.ts
> fix: add Switch and Textfield from DS

- lib/components/Avatar/Avatar.tsx
- lib/components/Avatar/avatar.module.css
- lib/components/Page/DashboardCard.tsx
- lib/components/Page/DashboardHeader.tsx
- package.json
> feat: Add skeleton to DashboardHeader and DashboardCards, pass className

- lib/components/Badge/badge.module.css
- https://github.com/Altinn/dialogporten-frontend/issues/2098
> fix(badge): prevent badge from growing in flex container

- lib/components/GlobalMenu/GlobalMenu.tsx
- lib/components/Header/Header.stories.tsx
- #https://github.com/Altinn/dialogporten-frontend/issues/2129
> fix: onClick on sub items in global menu should also close global menu

- examples/accountMenu.tsx
- examples/globalMenu.ts
- lib/components/GlobalMenu/AccountMenu.tsx
- lib/components/GlobalMenu/GlobalMenu.tsx
- lib/components/Layout/Layout.stories.tsx
- lib/components/Menu/Menu.tsx
- lib/components/Menu/MenuItems.tsx
- lib/components/Menu/MenuItemsVirtual.tsx
- lib/components/Toolbar/Toolbar.stories.tsx
Require adjustments in AF! 
https://github.com/Altinn/dialogporten-frontend/issues/1617
> fix: Add option for responsive virtualized list, refactor

- lib/components/Dialog/DialogListItem.tsx
- lib/components/List/ListItem.tsx
- lib/components/List/ListItemBase.tsx
Need to add an ID to list element for investigation about: 
https://github.com/Altinn/dialogporten-frontend/issues/1957
> fix: add ID to list item

- lib/components/List/ListItemHeader.tsx
- lib/components/List/listItemHeader.module.css
> fix: list item chevron

- lib/components/Button/Button.stories.tsx
- lib/components/Button/Button.tsx
- lib/components/Button/ButtonIcon.tsx
- lib/components/Button/ButtonLabel.tsx
- lib/components/Button/ComboButton.tsx
- lib/components/Button/IconButton.tsx
- lib/components/Button/button.module.css
- lib/components/Button/buttonBase.module.css
- lib/components/Button/buttonIcon.module.css
- lib/components/Button/comboButton.module.css
- lib/components/Button/iconButton.module.css
- lib/components/Forms/Forms.stories.tsx
- lib/components/Icon/Icon.tsx
- lib/components/Icon/IconOrAvatar.tsx
- lib/components/List/ListItem.stories.tsx
- lib/components/Menu/MenuItem.tsx
> fix: button size inherits from parent

- lib/components/List/ListItem.tsx
> fix: props definition and jsdoc for ListItem

- lib/components/List/List.tsx
- lib/components/List/list.module.css
- lib/components/Page/Breadcrumbs.stories.tsx
- lib/components/Page/Flex.stories.tsx
- lib/components/Page/Flex.tsx
- lib/components/Page/Grid.stories.tsx
- lib/components/Page/Grid.tsx
- lib/components/Page/List.stories.tsx
- lib/components/Page/Page.mdx
- lib/components/Page/flex.module.css
- lib/components/Page/grid.module.css
- lib/css/spacing.css
- lib/stories/Portal.stories.tsx
> fix: grid sizing, default spacing for list + grid

- examples/profile/useProfileLayout.tsx
- lib/components/Badge/Badge.stories.ts
- lib/components/Badge/badge.module.css
- lib/stories/Profile/Settings.stories.tsx
> fix: badge stories

- lib/components/Timeline/TimelineLink.tsx
- lib/components/Timeline/timelineLink.module.css
> fix: TimelineLink

- lib/components/List/ListItemHeader.tsx
> fix: change list item header to div

- examples/inbox/index.ts
- lib/components/Dialog/DialogListItem.stories.tsx
- lib/components/Dialog/DialogListItem.tsx
- lib/components/Dialog/DialogMetadata.stories.tsx
- lib/components/Dialog/DialogMetadata.tsx
sentCount
receivedCount
draftsLabel
> fix: dialog signals for transmissions sent + received

- examples/inbox/inboxFilters.tsx
- examples/inbox/inboxSection.tsx
- examples/inbox/index.ts
- examples/inbox/useInbox.tsx
- lib/components/Forms/Radio.stories.tsx
- lib/components/Menu/MenuOption.tsx
- lib/stories/Inbox.stories.tsx
- package.json
> feat: inbox-demo-nav

- examples/layout/useHeader.ts
- examples/layout/useLayout.tsx
- examples/portal/useHomepage.tsx
- lib/stories/Error.stories.tsx
- package.json
> feat: error pages

- .storybook/main.ts
- lib/components/Modal/ModalBase.tsx
- lib/stories/Profile.mdx
- lib/stories/Profile.stories.tsx
- lib/stories/Profile/Settings.stories.tsx
- package.json
> fix: profil modals + stories

- examples/activityLog/activityLogItems.tsx
- examples/admin/adminMenu.tsx
- examples/admin/useAdminLayout.tsx
- examples/profile/useProfileLayout.tsx
- lib/components/Account/AccountList.stories.tsx
- lib/components/Account/AccountList.tsx
- lib/components/Account/AccountSettingsList.stories.tsx
- lib/stories/Admin.stories.tsx
- lib/stories/Admin/Settings.stories.tsx
- lib/stories/Profile.mdx
- lib/stories/Profile.stories.tsx
- lib/stories/Profile/Settings.stories.tsx
- package.json
> fix: account list labels + profile docs

- examples/inbox/contextMenu.ts
- examples/inbox/useInbox.tsx
- lib/components/Dialog/DialogListItem.tsx
- lib/components/Dialog/dialogListItem.module.css
- lib/components/LayoutAction/actionFooter.module.css
- lib/components/LayoutAction/actionHeader.module.css
- lib/stories/Inbox.stories.tsx
> fix: inbox bulk mode story

- examples/inbox/contextMenu.ts
- examples/inbox/dialogContact.tsx
- examples/inbox/dialogs/brreg.tsx
- examples/inbox/dialogs/dialogs.tsx
- examples/inbox/dialogs/enova.tsx
- examples/inbox/dialogs/mattilsynet.tsx
- examples/inbox/dialogs/oslo.tsx
- examples/inbox/dialogs/skatt.tsx
- examples/inbox/dialogs/ssb.tsx
- examples/inbox/inboxMenu.tsx
- examples/inbox/inboxSection.tsx
- examples/inbox/seenByLog.tsx
- examples/inbox/useInbox.tsx
- examples/inbox/useInboxSearch.tsx
- lib/components/Dialog/Dialog.tsx
- lib/components/Dialog/DialogBody.tsx
- lib/components/Dialog/DialogHeader.tsx
- lib/components/Dialog/SeenByLogButton.tsx
- lib/components/Transmission/Transmission.tsx
- lib/components/Transmission/TransmissionType.tsx
- lib/stories/Inbox.stories.tsx
- package.json
> fix: dialog stories with content

- lib/components/ContextMenu/ContextMenu.tsx
- package.json
> fix: context menu was closing all other menus

- lib/components/Avatar/Avatar.tsx
- lib/components/Byline/Byline.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2328
> fix: DialogListItem avatar safari fix

- lib/components/Dialog/DialogBody.stories.tsx
- lib/components/Timeline/TimelineIcon.tsx
- lib/components/Timeline/timelineHeader.module.css
https://github.com/Altinn/dialogporten-frontend/issues/2340
> fix: fix wide logos on timelineHeader component

- lib/components/ContextMenu/ContextMenu.tsx
- lib/hooks/useClickOutside.ts
- package.json
https://github.com/Altinn/dialogporten-frontend/issues/2358
> fix: Modal not opening from contextMenu

- lib/components/ActivityLog/ActivityLog.tsx
> fix: Using item id instead of index for keys when mapping

- lib/components/ActivityLog/ActivityLog.tsx
- lib/components/ActivityLog/ActivityLogSegment.tsx
- lib/components/Dialog/DialogList.tsx
> fix: non unique keys

- lib/components/Forms/SearchField.tsx
- lib/components/Forms/searchField.module.css
- lib/components/Searchbar/SearchbarField.tsx
- lib/components/Searchbar/searchbarField.module.css
- package.json
fix clear and dismiss focus state on search bar and search field.
> fix: search field focus

- lib/components/Searchbar/Searchbar.tsx
> fix: escape function reopening searchbar

- examples/inbox/contextMenu.ts
- examples/inbox/useInbox.tsx
- lib/components/Dialog/DialogBody.tsx
- lib/components/Dialog/DialogHistorySegment.tsx
- lib/components/Timeline/TimelineSection.tsx
- lib/components/Timeline/TimelineSegment.tsx
- lib/components/Timeline/timelineBase.module.css
- package.json
> feat: add support for unread dialog body + timeline section and segment

- lib/components/Header/Header.tsx
- lib/hooks/useIsDesktop.ts
- package.json
> fix: ensure logical keyboard navigation order in global layout

- lib/components/List/ListItem.stories.tsx
- lib/components/List/listItemHeader.module.css
- package.json
Fix so that the pointer events passes through the focus element on ListItems
> fix(ListItem): add pointer-event none to linkFocus

- lib/components/Dropdown/drawerBody.module.css
- lib/components/Menu/menuItemsVirtual.module.css
https://github.com/Altinn/dialogporten-frontend/issues/2424
> fix: Remove outer scrollbar from accountList

- examples/inbox/useInboxBeta.tsx
- lib/components/Dashboard/DashboardHeader.stories.tsx
- lib/components/Dashboard/DashboardHeader.tsx
- package.json
> fix: loading state for description should render as section instead of p as it can contain react node

- lib/components/Typography/Heading.tsx
> fix: remove logging in header

- examples/inbox/inboxMenu.tsx
- examples/inbox/useInbox.tsx
- examples/inbox/useInboxLayout.tsx
- examples/inbox/useInboxSearch.tsx
- examples/layout/globalMenu.ts
- lib/components/Button/floatingActionButton.module.css
- lib/components/Dialog/DialogBody.tsx
- lib/components/Timeline/TimelineBase.tsx
- lib/components/Timeline/TimelineSection.tsx
- lib/components/Typography/typography.module.css
- lib/stories/Beta/Beta.stories.tsx
- lib/stories/Inbox.stories.tsx
- package.json
> fix: dialog body color + inbox demos

- examples/accounts/accountList.tsx
- examples/admin/useAdminLayout.tsx
- examples/profile/profileMenu.tsx
- lib/components/Account/AccountList.stories.tsx
- lib/components/Modal/ModalHeader.tsx
- lib/components/Settings/SettingsModal.tsx
- lib/stories/Admin.stories.tsx
- lib/stories/Admin/Settings.stories.tsx
- lib/stories/Profile.stories.tsx
- lib/stories/Profile/Settings.stories.tsx
> fix: company settings stories

- lib/components/Snackbar/SnackbarBase.tsx
- lib/components/Snackbar/SnackbarItem.tsx
https://github.com/Altinn/altinn-components/issues/588
> fix: Announce snackbar messages to screen readers

- lib/components/Button/ButtonBase.tsx
... which adds button-specific props like type, disabled, form ...
> fix(props): Make ButtonBaseProps extend React.ButtonHTMLAttributes<HTMLButtonElement>

- .storybook/preview.tsx
- lib/components/Header/Header.stories.tsx
- package.json
add default parameters to storybook/preview that fixes storybook crash issues
> fix: storybook crash issues

- lib/components/Modal/ModalBase.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2566#issuecomment-3323773853
> fix: support closing modal with esc key

- examples/admin/useAdminLayout.tsx
- examples/inbox/useInboxLayout.tsx
- examples/layout/useGlobalMenu.tsx
- examples/layout/useHeader.ts
- examples/layout/useLayout.tsx
- examples/profile/useProfile.tsx
- examples/profile/useProfileLayout.tsx
- package.json
> fix: add mobile menu to demo

- lib/components/index.ts
> fix: Add missing Alert export

- examples/inbox/useInboxLayout.tsx
- examples/profile/useProfileLayout.tsx
- lib/components/Layout/Layout.stories.tsx
- lib/components/Layout/Layout.tsx
- lib/components/Layout/LayoutSidebar.tsx
- lib/components/Layout/layoutSidebar.module.css
- package.json
Added "sticky"-prop on sidebar to make sidebar sticky when scrolling.
- #485
> feat: sticky sidebar

- lib/components/Alert/Alert.tsx
- lib/components/Alert/alert.module.css
- package.json
> chore: Adjust Alert styles

- lib/components/Avatar/Avatar.tsx
- lib/components/Avatar/avatar.module.css
- lib/components/Byline/Byline.tsx
> fix(byline): render time-tag only when data represents a date

- lib/components/Avatar/AvatarGroup.tsx
- lib/components/Byline/byline.module.css
- lib/components/Dialog/SeenByLog.stories.tsx
- lib/components/Dialog/SeenByLog.tsx
- lib/components/Dialog/SeenByLogItem.tsx
> fix: seen by log avatars

- lib/components/Dialog/DialogByline.tsx
- lib/components/Menu/menuSearch.module.css
> fix: search input size on mobile

- lib/components/Dialog/DialogByline.tsx
> chore: lint DialogByline

- examples/accounts/accounts.tsx
- examples/accounts/getAccount.tsx
- examples/accounts/useAccountsToolbar.tsx
- examples/settings/useSettings.tsx
- lib/components/Account/AccountList.tsx
- lib/components/GlobalMenu/BackButton.tsx
- lib/components/Settings/SettingsList.tsx
- lib/stories/Settings/Settings.stories.tsx
- package.json
> fix: settings details

- examples/settings/useSettings.tsx
> fix: account alerts sorting

- lib/components/Settings/Settings.mdx
> fix: settings docs
